### ISSUE TITLE
Negative `uniprob` in `renormalize_backoff` results in wrong unigrams logprobs in the output

### ISSUE THREAD

**Issue by slgao1010** [vsiivola/variKN#15]
Hi, I have an issue of using `simpleinterpolate2arpa`, the output has a bunch of unigrams with probs of `-60`, which doesn't seem correct. With further investigation, I found that the `renormalize_backoff` step modified their probabilities to below zero, which results in the `safelogprob` to output the default minimum safe value `-60`. Here are more details:

I modified [L443-446](https://github.com/vsiivola/variKN/blob/master/src/HashGram_tmpl.hh#L443-446) by adding the following cout line to generate logs:
```
    while (probs[1]->stepthrough(false, &gram[0], &gram_logprob)) {
      std::cout << "unigram: " << word(gram[0]).c_str() << " gram_logprob: " << gram_logprob << " uniprob: " << uniprob << " new prob: " << safelogprob(pow(10, gram_logprob) + uniprob) << std::endl;
      probs[1]->setvalue(&gram[0],
                         safelogprob(pow(10, gram_logprob) + uniprob));
    }
```
Taking the word “coeruleus” for example, in the log its probability (logprob) is modified as such:

```
unigram: coeruleus gram_logprob: -9.09763 uniprob: -8.24339e-10 new prob: -60
```

The uniprob is negative, and its value caused the modified probability `((pow(10, gram_logprob) + uniprob)` to be negative as well, which is below the threshold of `MINPROB= 1e-60`, therefore safelogprob outputs the default minimum safe logprob `-60`([code](https://github.com/vsiivola/variKN/blob/master/src/def.hh#L15-19)). 

It seems odd that there should ever be a negative probability. My guesses are
- either 1) if the `uniprob` is negative, it shouldn't be distributed equally to all unigrams, but should be distributed proportionally (to avoid unigrams with very small probability to have a negative probability); 
- or 2) there should never be a negative `uniprob` in the first place.

Could you shed some light on this issue please? Thanks!

**Comment by vsiivola** [comment]
Hi, thanks for reporting! It's been a while since I've looked at the details, but I don't think uniprob should ever be negative so there's something weird happening there. I suppose it is not easy to create a small training data set to reproduce the problem so it would be easy to debug?

**Comment by vsiivola** [comment]
The simpleinterpolate2arpa is approximate since it is not possible to express the real results of interpolation in arpa format. Maybe something goes wrong with the approximation and we should just make min uniprob 0.0. I'll try to take a closer look this week.

**Comment by vsiivola** [comment]
Looks like the probabilities for a prefix sum to > 1.0, maybe due to numerical imprecision. I think it would be probably enough to change to `const float uniprob = std::max(0.0f, (1.0f - explicit_probsum)) / probs[1]->num_entries();` 
https://github.com/vsiivola/variKN/blob/master/src/HashGram_tmpl.hh#L441

Probably should print a warning if explicit_probsum > 1.0 as well.

**Comment by slgao1010** [comment]
Thanks for replying so fast! What about changing the `if` statement to skip the uniprob redistribution if the `explicit_probsum = 1`, this can save the computations since it will be adding 0 anyway. I tried changes like following and the output seems normal: (starting from https://github.com/vsiivola/variKN/blob/master/src/HashGram_tmpl.hh#L439)
```
  } else if (1 > explicit_probsum > 0.001) {
    // Redistribute the remaining unigram mass equally accross unigrams
    const float uniprob = (1.0f - explicit_probsum) / probs[1]->num_entries();
    probs[1]->stepthrough(true, &gram[0], &gram_logprob);
    while (probs[1]->stepthrough(false, &gram[0], &gram_logprob)) {
      probs[1]->setvalue(&gram[0],
                         safelogprob(pow(10, gram_logprob) + uniprob));
    }
  } else if (explicit_probsum > 1) {
    std::cout << "WARNING: explicit_probsum is bigger than one: " << explicit_probsum << std::endl;
  }
```

**Comment by vsiivola** [comment]
@slgao1010 Would you have time to check if https://github.com/vsiivola/variKN/pull/16 looks reasonable to you?

**Comment by slgao1010** [comment]
@vsiivola Yes that seems to fix this issue, thanks! And a minor thing is that the word "weights" seems misspelt in the variable "models_and_weigths" in https://github.com/vsiivola/variKN/blob/master/app/simpleinterpolate2arpa.cc#L60 , maybe it can be a included as a quick fix as well?

**Comment by vsiivola** [comment]
Thanks! Fixed the typo as well.
