### ISSUE TITLE
varikn fails to install in fedora:40 docker

### ISSUE THREAD

**Issue by thfrkielikone** [vsiivola/variKN#20]
Hi,
I am trying to install varikn in a Fedora 40 docker container with python 3.12.3 and pip 23.3.2. Pip complains that certain information ("description", "authors", "license", "readme") is being sourced from outside the pyproject.toml and doesn't want to install (either through `pip install .` in the cloned repo or through the prebuilt package) it unless the source of that information is either moved to the pyproject.toml or marked as dynamic. Marking it as dynamic can seemingly be done per the patch below, which seems to be the easiest way to fix this (then it installs without complaint at least through `pip install .`). Can you reproduce this issue and would this be a reasonable fix?

```
diff --git a/pyproject.toml b/pyproject.toml
index b6f24b0..6547a30 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -8,7 +8,8 @@ build-backend = "setuptools.build_meta"
 
 [project]
 name = "varikn"
-dynamic = ["version"]
+dynamic = ["version", "description", "authors", "license", "readme"]
+
 
 [tool.setuptools_scm]
 write_to = "python-wrapper/varikn/_version.py"
```

**Comment by vsiivola** [comment]
The patch looks good to me, I'll try it this weekend and merge if there are no problems. Thanks!

**Comment by vsiivola** [comment]
It is in master, I hope it works now.

**Comment by vsiivola** [comment]
@svirpioj Should we do a version release to PYPI?

**Comment by thfrkielikone** [comment]
Thank you very much for looking into this this quickly!

**Comment by vsiivola** [comment]
I tagged version 1.2.1, let's see if the GitHub action for PYPI update still works 🤞

**Comment by vsiivola** [comment]
Ok 1.2.1 is in PYPI, but doing source install from PYPI requires that cmake and swig are first installed manually. I wonder if that's how it always worked or if something broke...

**Comment by vsiivola** [comment]
Looking at INSTALL.md I guess that's how it has always been.
